### PR TITLE
Adding frame delegate

### LINKED ISSUE #183: Feature request: capture a frame from the live preview buffer
Hey @piemonte I have a use case where i need to grab a frame from the live preview buffer in order to do some animation that doesn't require changing PBJVision modes. For example, lets say the user is in `PBJCameraModePhoto` and the user performs a gesture that requires immediate feedback/animation, in order to make animation smooth i basically need a freeze frame as a `UIImage` of the preview to make the animation fluid. 

I hacked my way into the project to get this working on my own fork, but i was wondering if you had any suggestions on how to clean this up, or if there is an easier route to take. 
https://github.com/rromanchuk/PBJVision/pull/3/files

### PR DESCRIPTION
**Pull request by benlachman**
Adds a very lightweight way to access raw frame sample buffers.

Fixes #183.

### CODE REVIEW

**Comment by benlachman** [comment]
This doesn't change any of the existing plumbing, just allows an outside `frameDelegate` to pull frames out of the capture stream. My main question is, does that addition of a synchronous delegate call have too much likelihood of mucking with performance. Thoughts?

**Comment by piemonte** [comment]
hey @benlachman! apologies on the delay, we really appreciate contributions. the direction you're thinking for having a separate delegate for more "advanced" features or editing functionality is nice for clarity. we'll go this direction.

**Comment by piemonte** [comment]
hey @benlachman thanks for this pull request, apologies i never got it merged in properly. there were some api changes i wanted specifically for this which i'll add and cite you for.  similar to how http://github.com/nextlevel/nextlevel handset frames.

thanks again.

**Comment by benlachman** [comment]
No worries. Glad was helpful to the process!

**Pull request closed without merging**
